version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
    - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: mimic
      MB_DB_HOST: postgres
    depends_on:
    - postgres
  postgres:
    image: postgres:latest
    command: >
      -c maintenance_work_mem=256MB
      -c max_wal_size=4GB
    container_name: postgres
    hostname: postgres
    volumes:
    - /home/mimiciv:/var/lib/postgresql/data
    - /data/mimiciv/icu:/docker-entrypoint-initdb.d/:ro
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mimic